### ISSUE TITLE
Bugs and improvements in version 3

### ISSUE THREAD

**Issue by VasilisKos** [forzzzzz/Calculator-You#10]
1. Moving the precision slider messes up the selected separator and decimal separator in the settings. Try choosing different separators and then moving the slider to see what I mean. 
2. Keys vibration and sound don't work. At least in my Android 13 Nokia X20. Changing the respective settings does nothing. 
3. The history option in the dots menu doesn't make sense, since there's a tab for that. It should be removed. The clear history option though, when in the history tab, is useful. Should be kept.
4. Please, add a quick settings tile, for launching the calculator. It's very convenient.
5. The phrase "System default" in the theme setting should be replaced with just "System", so that it fits a 2400x1080 screen. Now it doesn't, as you can see in the screenshot below: 

![Screenshot_20240808-181727](https://github.com/user-attachments/assets/2ce8fa7a-3727-4368-aad3-43a72a23708c)

That's all for now! Great job! 👏👍

**Comment by forzzzzz** [comment]
Hi, thanks!

1. I will fix it.
2. Maybe you have vibration turned on in your phone settings and sound accordingly. Everything works fine for me and on emulators.
3. Please describe in more detail.
4. Good idea. How would you like to see it?
5. I have a 2400x1080 screen. I don't have such problems. This depends on the interface scale and font size. Unfortunately, I won’t be able to please everyone; it’s very time- and resource-consuming. But these buttons can be scrolled.

**Comment by VasilisKos** [comment]
> Hi, thanks!
> 
> 1. I will fix it.
> 2. Maybe you have vibration turned on in your phone settings and sound accordingly. Everything works fine for me and on emulators.
> 3. Please describe in more detail.
> 4. Good idea. How would you like to see it?
> 5. I have a 2400x1080 screen. I don't have such problems. This depends on the interface scale and font size. Unfortunately, I won’t be able to please everyone; it’s very time- and resource-consuming. But these buttons can be scrolled.

1. Great! 
2. Yes, I have vibration and sound when pressing buttons turned off in Android settings. I got it. 
3. The 3 dots menu one the to right corner of the main screen includes "History". This is not necessary, since you have access to history more easily in the history tab. 
4. I think a tile of the same icon with the app would be fine. Like the Google Calculator. 
5. I don't think it would be so time consuming to just delete the word "default" from that text. That would make your app compatible with more devices. It would still make sense, and it's like that in most apps. "I don't have such problems" philosophy doesn't fit with the open source philosophy. You are not obliged to share your app. You can just make it for you. But sharing it with the open source community (and uploading it to Google Play) means that you want it to be used by others too. And thus be more compatible with most devices. 
Anyway, it's up to you of course. Thanks anyway.

**Comment by forzzzzz** [comment]
i released a new version [v3.1.0](https://github.com/forzzzzz/Calculator-You/releases/tag/v3.1.0)
