### ISSUE TITLE
App tile for quick settings?

### ISSUE THREAD

**Issue by rafnov** [forzzzzz/Calculator-You#11]
Could you please add app tile for quick settings?
Google calculator has it but is ugly. Yours is beautiful with material design. Would be great to run it from a tile.

**Comment by forzzzzz** [comment]
Okey, i will do it

**Comment by rafnov** [comment]
That's great!

**Comment by alabotski** [comment]
I'm also interested in this functionality!

**Comment by forzzzzz** [comment]
i released a new version [v3.1.0](https://github.com/forzzzzz/Calculator-You/releases/tag/v3.1.0)
