### ISSUE TITLE
Featurerequest: Optionally show the intermediate results in the history

### ISSUE THREAD

**Issue by JanWaldhorn** [forzzzzz/Calculator-You#15]
I am very happy with the beautiful app and glad that I finally found a successor to my previous favorite ([Calculator++](https://git.bubu1.eu/Bubu/android-calculatorpp)), which is apparently no longer being actively developed.

However. I noticed one change during the switch:
[Calculator++](https://git.bubu1.eu/Bubu/android-calculatorpp) also saves intermediate results in the history, Calculator-You only saves results that have been generated with the = button (see 7*7 example in the picture). Basically I understand the behavior. Nevertheless, I would be happy if there was an optional switch in the settings that also saves automatic results (see 8*8 example in the picture) in the history. That would help lazy people like me. 

Thanks a lot
![Screenshot_20240820-174243](https://github.com/user-attachments/assets/8a7ba816-a57d-4770-9508-a943e0bdff76)

**Comment by forzzzzz** [comment]
i released a new version [v3.1.0](https://github.com/forzzzzz/Calculator-You/releases/tag/v3.1.0)
