### ISSUE TITLE
Higher max value limit

### ISSUE THREAD

**Issue by PhilippKosarev** [forzzzzz/Calculator-You#16]
Is there a way to up the max value limit? As it stands you can't calculate factorial of 171.
Would this cause any performance issues?

**Comment by forzzzzz** [comment]
Hi! Thanks for your issue.

Increasing the max value limit is currently impossible. At the moment the limit is 1.7976931348623157*10E308 to 4.9406564584124654*10E-324. I don't know where else you can use larger numbers. If possible, this is not what this calculator is for. Yes, huge numbers like 1.3242*10E921932 can affect performance.

**Comment by PhilippKosarev** [comment]
I know no other calculator app is able to compute such high numbers, but weirdly enough the Lawnchair is apperantly able to handle much larger values without performance issues.
![screenshot-2024-09-13_14-29-10_1](https://github.com/user-attachments/assets/e480b8b3-05b2-426e-9eaf-ae595505151f)
I understand if this is not quite in the scope for this app.

**Comment by forzzzzz** [comment]
The reason for not removing the max value limit is not related to the loss of productivity, but there is no need and is limited by the mathematical library. If you no longer have a question. Please close the issue. Thank you!

**Comment by PhilippKosarev** [comment]
I see. Thank you for hearing me out :)
