### ISSUE TITLE
minor fastlane issue

### ISSUE THREAD

**Issue by IzzySoft** [forzzzzz/Calculator-You#2]
Please make sure to include the `.txt` file extension for your changelogs :wink:

**Comment by forzzzzz** [comment]
I made it

**Comment by IzzySoft** [comment]
Thanks! For other Fastlane hints (when needed), be welcome to the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) :smiley:
