### ISSUE TITLE
Unit convertion support

### ISSUE THREAD

**Issue by dontlookherepls** [forzzzzz/Calculator-You#3]
The title speak for himself.

**Comment by forzzzzz** [comment]
@dontlookherepls  This is good. I already have a super idea how this can be implemented. Maybe I will do this in the future❤️

**Comment by dontlookherepls** [comment]
This is wonderful (^^)

**Comment by forzzzzz** [comment]
@dontlookherepls I added a unit converter😎 https://github.com/forzzzzz/Calculator-You/releases/tag/v3.0.0
pls update and test it

**Comment by dontlookherepls** [comment]
Wonderful ! It's actually hella smart the way you've implemented it. The only thing that I'd like to be implemented are the sub multiples that go all the way down to 10^-12 and the multiples up to 10^12 (They are pretty crucial for me 😅). Oh right, I've noticed a stylistic discrepancy with the newly added drop-down menus (the edges aren't rounded) and they are kinda too long.

**Comment by forzzzzz** [comment]
> Wonderful ! It's actually hella smart the way you've implemented it. The only thing that I'd like to be implemented are the sub multiples that go all the way down to 10^-12 and the multiples up to 10^12 (They are pretty crucial for me 😅). Oh right, I've noticed a stylistic discrepancy with the newly added drop-down menus (the edges aren't rounded) and they are kinda too long.

Wow thanks! Maybe I will make the dropdown menu better. Сurrent dropdown menu is a default material3 menu.
