### ISSUE TITLE
Dont ignore comma/dot

### ISSUE THREAD

**Issue by Carlos-Rocha** [forzzzzz/Calculator-You#4]
In the default calculator one can multiply a number by ,5 and the result is the number multiplied by 0,5
Using this calculator the result is number x 5

**Comment by forzzzzz** [comment]
![Screenshot_20240714-224644_crDroid Home.png](https://github.com/user-attachments/assets/7a14fb28-8eb5-4276-bebe-807a3713f42b)

Maybe you made a mistake or I misunderstood you

**Comment by Carlos-Rocha** [comment]
Doesn't work here. After typing 20x can't type the comma. If I define (dot) as decimal separator I can't dot either

**Comment by forzzzzz** [comment]
I understood you.  This is a feature of the calculator.  But if it makes uncomfortable then I will fix it

**Comment by Carlos-Rocha** [comment]
It seems the "feature" doesn't work for you

**Comment by forzzzzz** [comment]
I will fix it

**Comment by forzzzzz** [comment]
@Carlos-Rocha I made it https://github.com/forzzzzz/Calculator-You/releases/tag/v3.0.0 pls update and test it
