### ISSUE TITLE
The Log function is not working properly for base 10 

### ISSUE THREAD

**Issue by Hardik1991913** [forzzzzz/Calculator-You#5]
In the calculator for any input for Log(10^(-n)) (base is 10) 
where n is any positive integer
the output is Always -1

**Input**: Log(10^(-n))
**Output**: -1

Here is the screenshot
![Calc_you](https://github.com/user-attachments/assets/990dd4b4-099f-4ad9-acb1-4938fb2b28a5)

**Comment by forzzzzz** [comment]
There is no problem with log.  I'm using https://github.com/Darkempire78/OpenCalc.  It has problems with power.  Therefore, it seemed to you that log was not working correctly.  It might be worth changing the library, but it will take a lot of time.  And I haven't found anything better than this yet

**Comment by Hardik1991913** [comment]
> There is no problem with log. I'm using https://github.com/Darkempire78/OpenCalc. It has problems with power. Therefore, it seemed to you that log was not working correctly. It might be worth changing the library, but it will take a lot of time. And I haven't found anything better than this yet

Thanks.

**Comment by Hardik1991913** [comment]
> There is no problem with log. I'm using https://github.com/Darkempire78/OpenCalc. It has problems with power. Therefore, it seemed to you that log was not working correctly. It might be worth changing the library, but it will take a lot of time. And I haven't found anything better than this yet

Thanks.

**Comment by forzzzzz** [comment]
@Hardik1991913 l fixed it https://github.com/forzzzzz/Calculator-You/releases/tag/v3.0.0 pls update and test it
