### ISSUE TITLE
Button clear "C"

### ISSUE THREAD

**Issue by axi776** [forzzzzz/Calculator-You#6]
Please add the C button to clear 1 character, the clean up button is not convenient in most cases

**Comment by forzzzzz** [comment]
Are you not happy with the current 1 character clear button?

**Comment by axi776** [comment]
![Новый точечный рисунок](https://github.com/user-attachments/assets/766155dd-5fe5-4372-b0f3-9438a7ab954e)
I’ve been using it for 2 days and haven’t seen this button, I just switched from the TechCalc+ application, there’s a button next to general deletion
