### ISSUE TITLE
[Bug] Spell checker is active

### ISSUE THREAD

**Issue by BluePixel4k** [forzzzzz/Calculator-You#7]
Inside the app, the spell checker of the keyboard is active for me:
<img src="https://github.com/user-attachments/assets/671b758b-dc3f-40c7-8d86-f6c276c38c6a" width="250" /> <img src="https://github.com/user-attachments/assets/ab032c18-7eb8-497d-8b0f-90d9ad3b2b4e" width="250" />

That's a but annoying and not intentional (I think).

I'm using the keyboard and spell checker of "[HeliBoard](https://github.com/Helium314/HeliBoard)".

**Comment by forzzzzz** [comment]
Thanks. I will fix it

**Comment by forzzzzz** [comment]
@BluePixel4k l fixed it https://github.com/forzzzzz/Calculator-You/releases/tag/v3.0.0 pls update and test it

**Comment by BluePixel4k** [comment]
Thank you! It works like a charm.
