### ISSUE TITLE
Exponent Zero not calculated correctly

### ISSUE THREAD

**Issue by heschy2** [forzzzzz/Calculator-You#8]
So, as far as I know, `x^0 = 1` for any value as x.
However the App says things like `5^(0) = 0.2` or `8^(0) = 0.125` which is (as far as I know) wrong.

![Screenshot_20240725-111206_Calculator You.png](https://github.com/user-attachments/assets/f81dada1-f168-4a84-8f6e-28d020626dd8)

**Comment by forzzzzz** [comment]
The problem is in the parser. I will mb change it

**Comment by forzzzzz** [comment]
@heschy2 l fixed it https://github.com/forzzzzz/Calculator-You/releases/tag/v3.0.0 pls update and test it

**Comment by heschy2** [comment]
Tested it, It works properly now. Thank you for your great work!
