### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [forzzzzz/Calculator-You#9]
I've checked your app if its build is reproducible (see: [Reproducible bulds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients?lang=en)), but while I was able to successfully generate the APK using `./gradlew assembleRelease`, the differences to the one provided at your latest release were huge. Was that APK really built from the commit the tag points to? If so, did I miss some build options? And if not, which commit was it?

APK diff of v2.2.5:

```diff
-------------------------------
--- /dev/fd/63  2024-07-16 19:22:08.580141577 +0200
+++ /dev/fd/62  2024-07-16 19:22:08.580141577 +0200
@@ -3,11 +3,11 @@
   META-INF/version-control-info.textproto
   32-bit CRC value (hex):                         8f81a905
   assets/dexopt/baseline.prof
-  32-bit CRC value (hex):                         5d1df039
+  32-bit CRC value (hex):                         892a6d92
   assets/dexopt/baseline.profm
   32-bit CRC value (hex):                         85ee51bf
   classes.dex
-  32-bit CRC value (hex):                         5ee43c7d
+  32-bit CRC value (hex):                         ff734188
   DebugProbesKt.bin
   32-bit CRC value (hex):                         d5ac4dc2
   META-INF/androidx.activity_activity-ktx.version
@@ -299,7 +299,7 @@
   res/5z.xml
   32-bit CRC value (hex):                         f0b2d9e9
   res/61.xml
-  32-bit CRC value (hex):                         7300d5fa
+  32-bit CRC value (hex):                         e98924b8
   res/62.9.png
   32-bit CRC value (hex):                         5418f824
   res/65.9.png
@@ -371,7 +371,7 @@
   res/9N.9.png
   32-bit CRC value (hex):                         52c5a6c3
   res/9O.xml
-  32-bit CRC value (hex):                         a96ff04f
+  32-bit CRC value (hex):                         dc0e670e
   res/9P.xml
   32-bit CRC value (hex):                         abde3c58
   res/9T.xml
@@ -401,7 +401,7 @@
   res/9z.xml
   32-bit CRC value (hex):                         e7c969d3
   res/A0.xml
-  32-bit CRC value (hex):                         b5e2fc69
+  32-bit CRC value (hex):                         41aa2b7b
   res/A1.xml
   32-bit CRC value (hex):                         ee094f1e
   res/A4.xml
@@ -457,11 +457,11 @@
   res/Cg.xml
   32-bit CRC value (hex):                         ba72a304
   res/Ci.xml
-  32-bit CRC value (hex):                         3141da6a
+  32-bit CRC value (hex):                         88dfe978
   res/Cp.xml
   32-bit CRC value (hex):                         2b66d651
   res/D-.xml
-  32-bit CRC value (hex):                         1b4ec609
…
```

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

**Comment by forzzzzz** [comment]
This APK was built from the commit the tag points to [https://github.com/forzzzzz/Calculator-You/commit/ef991e80457b884ed4025175fd9f1c05fe4eb781](ef991e8). I'm doing a major update. Can you wait a little? I will update and then maybe this problem won't exist. Or does this need to be done now?

**Comment by IzzySoft** [comment]
No rush, I'm not the prosecutor :see_no_evil: Sure, take your time. Maybe when preparing the release, check those hints to be on the safe side? Then just give me a ping when I shall check and try again.

**Comment by forzzzzz** [comment]
@IzzySoft I released a new version https://github.com/forzzzzz/Calculator-You/releases/tag/v3.0.0 i hope everything will be okay now

**Comment by IzzySoft** [comment]
Congrats, that's RB :partying_face: Thanks a lot!

![image](https://github.com/user-attachments/assets/3f04a1cb-ff46-4901-b573-3cffc6c0cfa0)

And [here's your special welcome message](https://floss.social/@IzzyOnDroid/112928650239245957) :smiley:
